language: python
python:
  - 2.7.9
  - 2.7.8
  - 2.7.6
  - 2.6
  - 3.3
  - 3.4
  - 3.5
  - nightly

script:
  - py.test -vv
  - py.test -vv -k test_https_warnings
  - py.test -vv -k test_verify

  - find . -name '*.pyc' -o -name '__pycache__' | xargs rm -rf

  - pip install --upgrade ndg-httpsclient pyasn1 'cryptography>=1.3.4'

  - py.test -vv -k test_https_warnings
  - py.test -vv -k test_verify

  - find . -name '*.pyc' -o -name '__pycache__' | xargs rm -rf

  - pip install --upgrade 'pyOpenSSL>=0.13' ndg-httpsclient pyasn1

  - py.test -vv
  - py.test -vv -k test_https_warnings
  - py.test -vv -k test_verify

notifications:
  email: false
