language: python
python:
  - 2.6
  - 2.7.6
  - 2.7.8
  - 2.7.9
  - 2.7.10
  - 2.7.11
  - 3.3
  - 3.4
  - 3.5
  - nightly
matrix:
  include:
    - python: '2.7_with_system_site_packages'
      env: DIST=precise
    - python: '2.7_with_system_site_packages'
      env: DIST=trusty
      dist: trusty
      sudo: required
    - language: python
      python: '2.7_with_system_site_packages'
      env: DIST=trusty+sid
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - python-ipaddr
            - python-openssl=0.13-2ubuntu6
            - python-requests
            - python-six
            - python-certifi
            - python-ndg-httpsclient
            - libssl1.0.2
            - python-cffi
            - python-enum34
            - python-idna
            - python-ipaddress
            - python-pyasn1
            - ca-certificates

before_script:
  - ls /home/travis/virtualenv/
script:
  - py.test -vv
  - rm -rf requests/packages/urllib3
  - pip install --upgrade urllib3 'pyOpenSSL>=0.13' ndg-httpsclient pyasn1
  - py.test -vv -k test_verify
  - git checkout requests/packages/urllib3
  - pip install -e '.[security]'
  - rm -rf requests/packages/urllib3
  - find . -name '*.pyc' -o -name '__pycache__' | xargs rm -rf
  - py.test -vv
  - py.test -vv -k test_verify
  - py.test -vv --import-urllib3 --inject-openssl
notifications:
  email: false
