language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - nightly
matrix:
  include:
    - python: '2.7_with_system_site_packages'
      env: DIST=precise
    - python: '2.7_with_system_site_packages'
      env: DIST=trusty
      dist: trusty
      sudo: required
script:
  - py.test -vv
  - rm -rf requests/packages/urllib3
  - pip install urllib3 'pyOpenSSL>=0.13' ndg-httpsclient pyasn1
  - py.test -vv
notifications:
  email: false
